"""Prepare the local Blender addon and project-scoped Codex configuration."""

import json
import shutil
from importlib.resources import files
from pathlib import Path

root = Path(__file__).resolve().parents[1]
local = root / ".tools"
addon = files("blender_mcp").joinpath("bundled/addon.py")
shutil.copyfile(str(addon), local / "blender_mcp_addon.py")

config = root / ".codex/config.toml"
config.parent.mkdir(exist_ok=True)
text = f'''# Generated by tools/configure_mcp.py for this checkout.
[mcp_servers.blender]
command = {json.dumps(str(local / "venv/bin/blender-mcp"))}
startup_timeout_sec = 30
tool_timeout_sec = 120
enabled_tools = ["get_addon_status", "get_scene_info", "get_object_info", "get_viewport_screenshot", "execute_blender_code"]

[mcp_servers.blender.env]
BLENDER_HOST = "127.0.0.1"
BLENDER_PORT = "9876"
BLENDER_MCP_DISABLE_TELEMETRY = "1"
BLENDER_MCP_SAFE_MODE = "1"
'''
if config.exists() and config.read_text() != text:
    raise SystemExit(f"Existing {config} differs; left unchanged. Merge the Blender entry manually.")
config.write_text(text)
print(f"MCP config: {config}")
print(f"Addon: {local / 'blender_mcp_addon.py'}")
